# Form implementation generated from reading ui file './windows/pass_word.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_pass_word(object):
    def setupUi(self, pass_word):
        pass_word.setObjectName("pass_word")
        pass_word.resize(702, 371)
        pass_word.setStyleSheet("background-color: rgb(171, 217, 252);")
        self.centralwidget = QtWidgets.QWidget(parent=pass_word)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 621, 31))
        self.label.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.pass_word_string = QtWidgets.QLabel(parent=self.centralwidget)
        self.pass_word_string.setGeometry(QtCore.QRect(26, 52, 661, 81))
        self.pass_word_string.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(103, 139, 255);")
        self.pass_word_string.setObjectName("pass_word_string")
        self.pass_word_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.pass_word_input.setGeometry(QtCore.QRect(20, 180, 431, 31))
        self.pass_word_input.setObjectName("pass_word_input")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 145, 151, 21))
        self.label_3.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.pass_word_checkAns = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pass_word_checkAns.setGeometry(QtCore.QRect(480, 180, 101, 31))
        self.pass_word_checkAns.setStyleSheet("background-color: rgb(103, 139, 255);")
        self.pass_word_checkAns.setObjectName("pass_word_checkAns")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 270, 81, 21))
        self.label_6.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.pass_word_result = QtWidgets.QLabel(parent=self.centralwidget)
        self.pass_word_result.setGeometry(QtCore.QRect(110, 270, 91, 21))
        self.pass_word_result.setText("")
        self.pass_word_result.setObjectName("pass_word_result")
        self.pass_word_dalee = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pass_word_dalee.setGeometry(QtCore.QRect(220, 270, 101, 31))
        self.pass_word_dalee.setObjectName("pass_word_dalee")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 310, 671, 20))
        self.label_2.setObjectName("label_2")
        self.pass_word_podskazka = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pass_word_podskazka.setGeometry(QtCore.QRect(590, 180, 81, 31))
        self.pass_word_podskazka.setObjectName("pass_word_podskazka")
        self.pass_word_podskazka_cou = QtWidgets.QLabel(parent=self.centralwidget)
        self.pass_word_podskazka_cou.setGeometry(QtCore.QRect(480, 230, 191, 16))
        self.pass_word_podskazka_cou.setObjectName("pass_word_podskazka_cou")
        pass_word.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=pass_word)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 702, 24))
        self.menubar.setObjectName("menubar")
        pass_word.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=pass_word)
        self.statusbar.setObjectName("statusbar")
        pass_word.setStatusBar(self.statusbar)

        self.retranslateUi(pass_word)
        QtCore.QMetaObject.connectSlotsByName(pass_word)

    def retranslateUi(self, pass_word):
        _translate = QtCore.QCoreApplication.translate
        pass_word.setWindowTitle(_translate("pass_word", "MainWindow"))
        self.label.setText(_translate("pass_word", "Перед вами строчка с пропущенным словом, вставьте вместо пропуска нужное слово."))
        self.pass_word_string.setText(_translate("pass_word", "<html><head/><body><p><br/></p></body></html>"))
        self.label_3.setText(_translate("pass_word", "Вставь слово:"))
        self.pass_word_checkAns.setText(_translate("pass_word", "Проверить"))
        self.label_6.setText(_translate("pass_word", "Результат:"))
        self.pass_word_dalee.setText(_translate("pass_word", "Далее"))
        self.label_2.setText(_translate("pass_word", "<html><head/><body><p><span style=\" color:#ff0000;\">(если ваше стихотворение на осетинском языке, во время записи слова замените символ &quot;æ&quot; на &quot;ае&quot;)</span></p></body></html>"))
        self.pass_word_podskazka.setText(_translate("pass_word", "Подсказка?"))
        self.pass_word_podskazka_cou.setText(_translate("pass_word", "Подсказок осталось:"))
