# Form implementation generated from reading ui file 'task_read.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SecondWindow2(object):
    def setupUi(self, SecondWindow):
        SecondWindow.setObjectName("SecondWindow")
        SecondWindow.setGeometry(QtCore.QRect(0, 0, 875, 576))
        SecondWindow.setStyleSheet("background-color: rgb(171, 217, 252);")
        self.centralwidget = QtWidgets.QWidget(parent=SecondWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.task_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.task_1.setGeometry(QtCore.QRect(40, 10, 751, 20))
        self.task_1.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";")
        self.task_1.setObjectName("task_1")
        self.four_string_original = QtWidgets.QLabel(parent=self.centralwidget)
        self.four_string_original.setGeometry(QtCore.QRect(50, 40, 701, 261))

        self.four_string_original.setObjectName("four_string_original")
        self.four_string_original.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.ready_read = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ready_read.setGeometry(QtCore.QRect(370, 340, 75, 23))
        self.ready_read.setStyleSheet("background-color: rgb(62, 149, 255);")
        self.ready_read.setObjectName("ready_read")
        SecondWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=SecondWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        SecondWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=SecondWindow)
        self.statusbar.setObjectName("statusbar")
        SecondWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SecondWindow)
        QtCore.QMetaObject.connectSlotsByName(SecondWindow)

    def retranslateUi(self, SecondWindow):
        _translate = QtCore.QCoreApplication.translate
        SecondWindow.setWindowTitle(_translate("SecondWindow2", "MainWindow"))
        self.task_1.setText(_translate("SecondWindow2", "Перед вами первые 4 строчки стихотворения. Внимательно прочитатйте их."))
        self.ready_read.setText(_translate("SecondWindow2", "Прочитал"))
