# Form implementation generated from reading ui file './windows/random_string_win.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_random_string_win(object):
    def setupUi(self, random_string_win):
        random_string_win.setObjectName("random_string_win")
        random_string_win.resize(858, 575)
        random_string_win.setStyleSheet("background-color: rgb(171, 217, 252);")
        self.centralwidget = QtWidgets.QWidget(parent=random_string_win)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 741, 41))
        self.label_5.setStyleSheet("color: rgb(37, 27, 159);\n"
"font: 75 15pt \"MS Shell Dlg 2\";\n"
"")
        self.label_5.setObjectName("label_5")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 581, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.random_str_win_1 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.random_str_win_1.setText("")
        self.random_str_win_1.setObjectName("random_str_win_1")
        self.verticalLayout.addWidget(self.random_str_win_1)
        self.random_str_win_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.random_str_win_2.setText("")
        self.random_str_win_2.setObjectName("random_str_win_2")
        self.verticalLayout.addWidget(self.random_str_win_2)
        self.random_str_win_4 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.random_str_win_4.setText("")
        self.random_str_win_4.setObjectName("random_str_win_4")
        self.verticalLayout.addWidget(self.random_str_win_4)
        self.random_str_win_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.random_str_win_3.setText("")
        self.random_str_win_3.setObjectName("random_str_win_3")
        self.verticalLayout.addWidget(self.random_str_win_3)
        self.random_string_num1 = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.random_string_num1.setGeometry(QtCore.QRect(600, 87, 119, 21))
        self.random_string_num1.setObjectName("random_string_num1")
        self.random_string_num2 = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.random_string_num2.setGeometry(QtCore.QRect(600, 200, 119, 21))
        self.random_string_num2.setObjectName("random_string_num2")
        self.random_string_num3 = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.random_string_num3.setGeometry(QtCore.QRect(600, 310, 119, 21))
        self.random_string_num3.setObjectName("random_string_num3")
        self.random_string_num4 = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.random_string_num4.setGeometry(QtCore.QRect(600, 420, 119, 21))
        self.random_string_num4.setObjectName("random_string_num4")
        self.random_string_win_checkBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.random_string_win_checkBtn.setGeometry(QtCore.QRect(500, 490, 91, 31))
        self.random_string_win_checkBtn.setStyleSheet("background-color: rgb(103, 139, 255);")
        self.random_string_win_checkBtn.setObjectName("random_string_win_checkBtn")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 500, 161, 20))
        self.label.setText("")
        self.label.setObjectName("label")
        self.dalee_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.dalee_btn.setGeometry(QtCore.QRect(610, 490, 113, 32))
        self.dalee_btn.setObjectName("dalee_btn")
        random_string_win.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=random_string_win)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 858, 24))
        self.menubar.setObjectName("menubar")
        random_string_win.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=random_string_win)
        self.statusbar.setObjectName("statusbar")
        random_string_win.setStatusBar(self.statusbar)

        self.retranslateUi(random_string_win)
        QtCore.QMetaObject.connectSlotsByName(random_string_win)

    def retranslateUi(self, random_string_win):
        _translate = QtCore.QCoreApplication.translate
        random_string_win.setWindowTitle(_translate("random_string_win", "MainWindow"))
        self.label_5.setText(_translate("random_string_win", "Перед вами 4 строчки стихоторения, написанные вразброс, расставьте их в правильном порядке"))
        self.random_string_win_checkBtn.setText(_translate("random_string_win", "Проверить"))
        self.dalee_btn.setText(_translate("random_string_win", "Далее->"))
